### ISSUE TITLE
GlassCode is not compatible with 2021.2 releases

### ISSUE THREAD

**Issue by dacanizares** [gileli121/GlassCode#7]
Same issue as: https://github.com/gileli121/GlassCode/issues/5
BUT version 2021.2.

As EncryptedCurse said: 

In the meantime, I was able to get around this using these steps:
1. Download the latest plugin ZIP from JetBrains Marketplace
2. Open the archive and navigate to glasscode/lib/glasscode-1.2.3-SNAPSHOT.jar/META-INF
3. Edit until-build in plugin.xml to say "212.*" instead of "211.*"
4. Install plugin ZIP from disk

**Comment by gileli121** [comment]
Thanks for the report.
I will fix it soon

**Comment by gileli121** [comment]
@dacanizares 
I forgot to update that it fixed.
Please let me know if it works fine now

**Comment by dacanizares** [comment]
It's working! Thank you.

**Comment by gileli121** [comment]
Great!
Issue closed

**Comment by YummyYakuza** [comment]
Glasscode is not compatible with latest versions of jetbrains ide
